# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 425)
        self.printTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.printTextBrowser.setGeometry(QtCore.QRect(10, 110, 701, 311))
        self.printTextBrowser.setTabletTracking(False)
        self.printTextBrowser.setObjectName("printTextBrowser")
        self.sourcePathLineEdit = QtWidgets.QLineEdit(Dialog)
        self.sourcePathLineEdit.setGeometry(QtCore.QRect(102, 10, 511, 21))
        self.sourcePathLineEdit.setObjectName("sourcePathLineEdit")
        self.checkPushButton = QtWidgets.QPushButton(Dialog)
        self.checkPushButton.setGeometry(QtCore.QRect(630, 10, 75, 51))
        self.checkPushButton.setObjectName("checkPushButton")
        self.startPushButton = QtWidgets.QPushButton(Dialog)
        self.startPushButton.setGeometry(QtCore.QRect(10, 72, 341, 31))
        self.startPushButton.setAutoRepeatInterval(100)
        self.startPushButton.setObjectName("startPushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.label_2.setObjectName("label_2")
        self.backupPathLineEdit = QtWidgets.QLineEdit(Dialog)
        self.backupPathLineEdit.setGeometry(QtCore.QRect(100, 40, 511, 21))
        self.backupPathLineEdit.setObjectName("backupPathLineEdit")
        self.stopPushButton = QtWidgets.QPushButton(Dialog)
        self.stopPushButton.setGeometry(QtCore.QRect(370, 72, 341, 31))
        self.stopPushButton.setObjectName("stopPushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DMP自动部署"))
        self.sourcePathLineEdit.setText(_translate("Dialog", "D:\\WorkSpace\\Android TV\\cvt_app\\multi_media_player\\app\\build\\outputs\\apk\\umc\\release\\"))
        self.checkPushButton.setText(_translate("Dialog", "Check"))
        self.startPushButton.setText(_translate("Dialog", "Start"))
        self.label.setText(_translate("Dialog", "ApkSourcePath:"))
        self.label_2.setText(_translate("Dialog", "ApkBackupPath:"))
        self.backupPathLineEdit.setText(_translate("Dialog", "D:\\"))
        self.stopPushButton.setText(_translate("Dialog", "Stop"))
